name: classification_models
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.9
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pywin32=307
  - pyzmq=26.2.0
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - altair==5.5.0
      - attrs==24.2.0
      - blinker==1.9.0
      - cachetools==5.5.0
      - category-encoders==2.6.4
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.55.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.3
      - mdurl==0.1.2
      - narwhals==1.15.1
      - numpy==1.26.4
      - pandas==2.2.2
      - patsy==1.0.1
      - pillow==11.0.0
      - plotly==5.24.1
      - protobuf==5.29.0
      - pyarrow==18.1.0
      - pydeck==0.9.1
      - pyparsing==3.2.0
      - pytz==2024.2
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.21.0
      - scikit-learn==1.4.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - smmap==5.0.1
      - statsmodels==0.14.4
      - streamlit==1.40.2
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - tqdm==4.67.1
      - tzdata==2024.2
      - urllib3==2.2.3
      - watchdog==6.0.0
      - xgboost==2.1.3
      - flask==3.1.0